<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <!-- The published output files, compiled unmodified -->
    <Compile Include="../../outputs/E-opus-2026-04-22/*.cs" />
  </ItemGroup>
</Project>
